runtime: python39
default_expiration: 365d

handlers:
  - url: /
    upload: index.html
    static_files: index.html
    secure: always
    redirect_http_response_code: 301

  - url: /favicon.png
    upload: favicon.png
    static_files: favicon.png
    secure: always
    redirect_http_response_code: 301

  - url: /dist/(.*)
    upload: dist/(.*)
    static_files: dist/\1
    secure: always
    redirect_http_response_code: 301
