runtime: python39
default_expiration: 365d

handlers:
  - url: /
    upload: index.html
    static_files: index.html

  - url: /favicon.png
    upload: favicon.png
    static_files: favicon.png

  - url: /dist/(.*)
    upload: dist/(.*)
    static_files: dist/\1
